"""empty message

Revision ID: 0c97c1fe0312
Revises: ed2131cab319
Create Date: 2023-09-10 15:44:30.540858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c97c1fe0312'
down_revision = 'ed2131cab319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enroll_candidates', sa.Column('birthDate', sa.Text(), nullable=True))
    op.add_column('enroll_candidates', sa.Column('role', sa.Text(), nullable=True))
    op.add_column('enroll_candidates', sa.Column('studentExp', sa.Text(), nullable=True))
    op.alter_column('media_list', 'media_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=1024),
               comment='视频ID',
               existing_comment='视频ID, 姓名的md5',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_list', 'media_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=1024),
               comment='视频ID, 姓名的md5',
               existing_comment='视频ID',
               existing_nullable=False)
    op.drop_column('enroll_candidates', 'studentExp')
    op.drop_column('enroll_candidates', 'role')
    op.drop_column('enroll_candidates', 'birthDate')
    # ### end Alembic commands ###
