"""empty message

Revision ID: 1025b1c153ab
Revises: 0c97c1fe0312
Create Date: 2023-09-10 15:50:57.726583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1025b1c153ab'
down_revision = '0c97c1fe0312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enroll_candidates', sa.Column('other_advantage', sa.Text(), nullable=True))
    op.add_column('enroll_candidates', sa.Column('birth_date', sa.Text(), nullable=True))
    op.add_column('enroll_candidates', sa.Column('student_exp', sa.Text(), nullable=True))
    op.drop_column('enroll_candidates', 'otherAdvantage')
    op.drop_column('enroll_candidates', 'birthDate')
    op.drop_column('enroll_candidates', 'studentExp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enroll_candidates', sa.Column('studentExp', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
    op.add_column('enroll_candidates', sa.Column('birthDate', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
    op.add_column('enroll_candidates', sa.Column('otherAdvantage', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
    op.drop_column('enroll_candidates', 'student_exp')
    op.drop_column('enroll_candidates', 'birth_date')
    op.drop_column('enroll_candidates', 'other_advantage')
    # ### end Alembic commands ###
