"""empty message

Revision ID: 42f2541a6329
Revises: 7ff4359e89b7
Create Date: 2023-01-18 19:15:29.316343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f2541a6329'
down_revision = '7ff4359e89b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_list', sa.Column('uuid', sa.String(length=24), nullable=False, comment='uuid'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_list', 'uuid')
    # ### end Alembic commands ###
