"""empty message

Revision ID: 7ff4359e89b7
Revises: 86b674696e64
Create Date: 2022-12-28 20:49:14.290837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff4359e89b7'
down_revision = '86b674696e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_list',
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('update_cnt', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='更新次数'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标记'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False, comment='姓名'),
    sa.Column('file_name', sa.String(length=60), nullable=False, comment='视频文件路径'),
    sa.Column('media_id', sa.String(length=1024), nullable=False, comment='视频ID, 姓名的md5'),
    sa.Column('status', sa.Integer(), nullable=False, comment='视频状态, 如果为1表明制作完成'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_list')
    # ### end Alembic commands ###
