"""empty message

Revision ID: 86b674696e64
Revises: 
Create Date: 2022-10-03 00:00:10.579644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b674696e64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enroll_depts',
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('update_cnt', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='更新次数'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标记'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=20), nullable=False, comment='部门名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enroll_turns',
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('update_cnt', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='更新次数'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标记'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_name', sa.String(length=40), nullable=False, comment='招新批次名称'),
    sa.Column('activated', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='是否为当前批次'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enroll_candidates',
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('update_cnt', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='更新次数'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标记'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.String(length=5), nullable=False),
    sa.Column('faculty', sa.String(length=20), nullable=False),
    sa.Column('first_choice', sa.String(length=20), nullable=False, comment='第一志愿'),
    sa.Column('second_choice', sa.String(length=20), nullable=True, comment='第二志愿'),
    sa.Column('third_choice', sa.String(length=20), nullable=True, comment='第三志愿'),
    sa.Column('tel', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('allow_adjust', sa.Boolean(), nullable=False, comment='是否服从调剂'),
    sa.Column('info', sa.Text(), nullable=True, comment='特长等详细信息'),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['enroll_turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enroll_candidates')
    op.drop_table('enroll_turns')
    op.drop_table('enroll_depts')
    # ### end Alembic commands ###
