"""empty message

Revision ID: a7fe523884f1
Revises: ed2131cab319
Create Date: 2023-09-11 01:41:46.916390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7fe523884f1'
down_revision = 'ed2131cab319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enroll_candidates', sa.Column('other_advantage', sa.Text(), nullable=True))
    op.add_column('enroll_candidates', sa.Column('birth_date', sa.Text(), nullable=True))
    op.add_column('enroll_candidates', sa.Column('role', sa.Text(), nullable=True))
    op.add_column('enroll_candidates', sa.Column('student_exp', sa.Text(), nullable=True))
    op.drop_column('enroll_candidates', 'otherAdvantage')
    op.alter_column('media_list', 'media_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=1024),
               comment='视频ID',
               existing_comment='视频ID, 姓名的md5',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_list', 'media_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=1024),
               comment='视频ID, 姓名的md5',
               existing_comment='视频ID',
               existing_nullable=False)
    op.add_column('enroll_candidates', sa.Column('otherAdvantage', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True))
    op.drop_column('enroll_candidates', 'student_exp')
    op.drop_column('enroll_candidates', 'role')
    op.drop_column('enroll_candidates', 'birth_date')
    op.drop_column('enroll_candidates', 'other_advantage')
    # ### end Alembic commands ###
