"""empty message

Revision ID: ed2131cab319
Revises: 42f2541a6329
Create Date: 2023-01-18 19:20:14.498267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2131cab319'
down_revision = '42f2541a6329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_list', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_list', sa.Column('uuid', sa.VARCHAR(length=24), nullable=False))
    # ### end Alembic commands ###
